<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur10_admittance_controller_demo</name>
  <version>0.1.0</version>
  <description>An application package for the UR10 under the admittance controller</description>
  <author email="lpagliara@unisa.it">Lorenzo Pagliara</author>
  <maintainer email="eferrentino@unisa.it">Enrico Ferrentino</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>acg_admittance_controller</exec_depend>
  <exec_depend>acg_resources_ur10_moveit_config</exec_depend>
  <exec_depend>cartesian_pose_controller</exec_depend>
  <exec_depend>pid_controller</exec_depend>
  <exec_depend>plotjuggler_ros</exec_depend>
  <exec_depend>reference_generator</exec_depend>
  <exec_depend>robotiq_force_torque_sensor</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
